window.COCO_CHOICE_COPY={
  "ko": {
    "chooseTitle": "어떤 우도를 달리고 싶으세요?",
    "chooseIntro": "함께 온 사람도, 여행의 속도도 다르니까. 나에게 맞는 한 대를 골라보세요.",
    "cocoName": "코코 (1인승)",
    "famiName": "파미 (2인승)",
    "openName": "오픈카 (2인승)",
    "cocoBadge": "각자 타는 자유",
    "famiBadge": "쉬운 운전",
    "openBadge": "함께 맞는 바람",
    "cocoSub": "같이 와도, 운전은 각자!",
    "famiSub": "운전은 가볍게, 둘이 편안하게",
    "openSub": "나란히, 바닷바람 속으로",
    "cocoLead": "쉽게 익히고, 내 마음대로 달리는 재미. 우도의 자유를 가장 가깝게 느끼는 미니 바이크.",
    "cocoBody": "자전거의 균형 감각이 익숙하다면 코코에 도전해 보세요. 커플도 친구도 한 사람 한 대! 함께 달리면서도 속도와 멈추는 순간은 내가 정해요. 코코나라에서 가장 많이 선택하는 차량이에요.",
    "cocoNote": "운전면허와 이용 기준을 확인하고, 현장 안내에 따라 충분히 연습한 뒤 출발해 주세요.",
    "famiLead": "세 차종 중 조작이 가장 쉬워, 운전이 낯선 두 분께 추천해요.",
    "famiBody": "지붕과 가림막이 햇빛과 바람을 덜어줘요. 얼굴에 닿는 바람과 헤어·메이크업 걱정을 줄이고 싶은 날, 편안하게 우도를 돌아보세요.",
    "openLead": "스쿠터 운전 경험이 있는 두 분께 추천하는 오픈형 전기차.",
    "openBody": "가림막 없이 바닷바람을 함께 느끼고 싶은 날. 나란히 앉아 우도의 풍경을 즐겨보세요.",
    "book": "예약하기 ↗",
    "cocoBook": "코코 예약하기",
    "famiBook": "파미 예약하기",
    "openBook": "오픈카 예약하기",
    "iceTab": "우도땅콩 아이스크림",
    "iceNavAria": "우도 땅콩아이스크림 · 달콤아재",
    "brandTitle": "우도를 더 가까이, 여행은 더 자유롭게.",
    "brandIntro": "코코나라는 섬 속의 섬, 우도의 아름다움을 더 많은 분과 나누고 싶어 시작했습니다.",
    "brandBody": "오래 걷는 여행이 부담스러운 분도, 아이와 함께 온 가족도, 연인과 친구도. 각자에게 맞는 방법으로 우도를 만나고, 자기만의 속도로 기억을 쌓았으면 합니다.",
    "brandJourney": "코코나라로 바다를 달리고, 달콤아재에서 우도의 맛을 느끼고, 훈데르트바서에서 자연과 예술을 만나는 하루. 이동과 맛, 쉼이 이어지는 우도 여행을 전해드립니다.",
    "brandWish": "아이들에게는 책 밖의 자연을 오감으로 만나는 시간을, 사랑하는 사람들에게는 오래 남을 추억을. 우도를 즐기는 마음이 이 섬과 자연을 아끼는 마음으로 이어지길 바랍니다.",
    "journeyRide": "코코나라 · 자유로운 이동",
    "journeyTaste": "달콤아재 · 우도의 맛",
    "journeyArt": "훈데르트바서 · 자연과 예술",
    "gpsLabel": "내 위치",
    "gpsEnable": "내 위치 켜기",
    "gpsDisable": "내 위치 끄기",
    "headingLabel": "이동 방향",
    "headingHint": "이동 중에는 화살표로 이동 방향을 알려드려요.",
    "rentalTab": "대여장비",
    "exhibitionTab": "전시관",
    "dalkomDirections": "네이버 지도 길찾기",
    "dalkomWeb": "앱 없이 매장 위치 보기"
  },
  "en": {
    "chooseTitle": "How would you like to explore Udo?",
    "chooseIntro": "Different company, different pace. Find the ride that suits your trip.",
    "cocoName": "Coco (1 seat)",
    "famiName": "Fami (2 seats)",
    "openName": "Open-top (2 seats)",
    "cocoBadge": "Your own ride",
    "famiBadge": "Easy to drive",
    "openBadge": "Share the sea breeze",
    "cocoSub": "Come together, ride your own!",
    "famiSub": "Easy driving, comfort for two",
    "openSub": "Side by side in the sea breeze",
    "cocoLead": "Easy to learn, with the fun of riding at your own pace. A mini bike that brings you closer to the freedom of Udo.",
    "cocoBody": "If balancing on a bicycle feels familiar, give Coco a try. With your partner or friends, it’s one bike each! Ride together while choosing your own speed and when to stop. This is the most popular choice at Coconara.",
    "cocoNote": "Check the driving licence and rental requirements, and practise thoroughly with the staff’s guidance before setting off.",
    "famiLead": "The easiest of our three models to operate, recommended for two visitors who are less familiar with driving.",
    "famiBody": "The roof and screens help reduce exposure to sunlight and wind. When you want less wind in your face and less worry about your hair and makeup, explore Udo in comfort.",
    "openLead": "An open electric vehicle recommended for two visitors with scooter-riding experience.",
    "openBody": "For days when you want to feel the sea breeze together, without a screen between you and the wind. Sit side by side and enjoy Udo’s scenery.",
    "book": "Book now ↗",
    "cocoBook": "Book Coco",
    "famiBook": "Book Fami",
    "openBook": "Book Open-top",
    "iceTab": "Udo peanut ice cream",
    "iceNavAria": "Udo peanut ice cream · Dalkom Ajae",
    "brandTitle": "Closer to Udo. More freedom to explore.",
    "brandIntro": "Coconara began with a wish to share the beauty of Udo, an island off an island, with more people.",
    "brandBody": "For those who find long walks tiring, families visiting with children, couples and friends. We hope everyone can discover Udo in a way that suits them and make memories at their own pace.",
    "brandJourney": "Ride along the sea with Coconara, taste Udo at Dalkom Ajae, and discover nature and art at Hundertwasser. We bring together getting around, good food and moments of rest for your day on Udo.",
    "brandWish": "For children, a chance to experience nature beyond books with all five senses. For loved ones, memories that last. We hope the joy of exploring Udo grows into a love for this island and its natural world.",
    "journeyRide": "Coconara · Freedom to explore",
    "journeyTaste": "Dalkom Ajae · A taste of Udo",
    "journeyArt": "Hundertwasser · Nature and art",
    "gpsLabel": "My location",
    "gpsEnable": "Show my location",
    "gpsDisable": "Turn location off",
    "headingLabel": "Direction of travel",
    "headingHint": "While you move, an arrow shows your direction of travel.",
    "rentalTab": "Rentals",
    "exhibitionTab": "Exhibitions",
    "dalkomDirections": "Directions in NAVER Maps",
    "dalkomWeb": "View the shop without the app"
  },
  "ms": {
    "chooseTitle": "Bagaimana anda ingin menerokai Udo?",
    "chooseIntro": "Teman perjalanan dan rentak percutian setiap orang berbeza. Pilih kenderaan yang sesuai untuk anda.",
    "cocoName": "Coco (1 tempat duduk)",
    "famiName": "Fami (2 tempat duduk)",
    "openName": "Kereta terbuka (2 tempat duduk)",
    "cocoBadge": "Bebas menunggang sendiri",
    "famiBadge": "Mudah dipandu",
    "openBadge": "Nikmati bayu bersama",
    "cocoSub": "Datang bersama, tunggang sendiri!",
    "famiSub": "Mudah dipandu, selesa berdua",
    "openSub": "Bersebelahan, menikmati bayu laut",
    "cocoLead": "Mudah dipelajari, seronok ditunggang mengikut rentak sendiri. Motosikal mini untuk merasai kebebasan Udo dengan lebih dekat.",
    "cocoBody": "Jika anda biasa mengimbangi basikal, cubalah Coco. Bersama pasangan atau rakan, satu kenderaan untuk setiap orang! Menunggang bersama sambil menentukan kelajuan dan masa untuk berhenti sendiri. Inilah kenderaan yang paling banyak dipilih di Coconara.",
    "cocoNote": "Semak syarat lesen memandu dan penggunaan, kemudian berlatih secukupnya mengikut panduan petugas sebelum bertolak.",
    "famiLead": "Paling mudah dikendalikan antara tiga model kami, disyorkan untuk dua pengunjung yang kurang biasa memandu.",
    "famiBody": "Bumbung dan pengadang membantu mengurangkan cahaya matahari dan angin. Jika anda mahu mengurangkan tiupan angin ke muka serta kurang risau tentang rambut dan solekan, jelajahi Udo dengan selesa.",
    "openLead": "Kenderaan elektrik terbuka yang disyorkan untuk dua pengunjung yang berpengalaman menunggang skuter.",
    "openBody": "Untuk hari anda ingin merasai bayu laut bersama tanpa pengadang. Duduk bersebelahan dan nikmati pemandangan Udo.",
    "book": "Tempah sekarang ↗",
    "cocoBook": "Tempah Coco",
    "famiBook": "Tempah Fami",
    "openBook": "Tempah kereta terbuka",
    "iceTab": "Aiskrim kacang Udo",
    "iceNavAria": "Aiskrim kacang tanah Udo · Dalkom Ajae",
    "brandTitle": "Lebih dekat dengan Udo, lebih bebas meneroka.",
    "brandIntro": "Coconara bermula dengan hasrat untuk berkongsi keindahan Udo, sebuah pulau di luar pulau Jeju, dengan lebih ramai orang.",
    "brandBody": "Bagi mereka yang sukar berjalan jauh, keluarga yang datang bersama anak-anak, pasangan dan rakan-rakan. Kami berharap setiap orang dapat mengenali Udo dengan cara yang sesuai dan mengumpul kenangan mengikut rentak sendiri.",
    "brandJourney": "Nikmati perjalanan di tepi laut bersama Coconara, rasai keenakan Udo di Dalkom Ajae, dan temui alam serta seni di Hundertwasser. Kami menghubungkan perjalanan, cita rasa dan waktu berehat untuk percutian anda di Udo.",
    "brandWish": "Untuk anak-anak, peluang mengenali alam di luar buku melalui kelima-lima deria. Untuk insan tersayang, kenangan yang berkekalan. Semoga kegembiraan menikmati Udo menumbuhkan rasa sayang terhadap pulau ini dan alamnya.",
    "journeyRide": "Coconara · Bebas meneroka",
    "journeyTaste": "Dalkom Ajae · Cita rasa Udo",
    "journeyArt": "Hundertwasser · Alam dan seni",
    "gpsLabel": "Lokasi saya",
    "gpsEnable": "Tunjukkan lokasi saya",
    "gpsDisable": "Matikan lokasi",
    "headingLabel": "Arah pergerakan",
    "headingHint": "Semasa anda bergerak, anak panah menunjukkan arah pergerakan anda.",
    "rentalTab": "Sewaan",
    "exhibitionTab": "Pameran",
    "dalkomDirections": "Arah di NAVER Maps",
    "dalkomWeb": "Lihat lokasi kedai tanpa aplikasi"
  },
  "zh-HK": {
    "chooseTitle": "你想怎樣暢遊牛島？",
    "chooseIntro": "同行的人不同，旅行的步調也不同。選一輛適合你的車吧。",
    "cocoName": "Coco（單人座）",
    "famiName": "Fami（雙人座）",
    "openName": "開篷車（雙人座）",
    "cocoBadge": "各自騎行更自在",
    "famiBadge": "操作容易",
    "openBadge": "一起迎着海風",
    "cocoSub": "一起來，各自騎！",
    "famiSub": "輕鬆駕駛，兩人舒適同行",
    "openSub": "並肩而坐，迎着海風",
    "cocoLead": "容易上手，享受隨心騎行的樂趣。騎上迷你電單車，貼近牛島的自在。",
    "cocoBody": "如果你已熟悉踩單車的平衡感，不妨試試 Coco。伴侶或朋友同行，都可一人一輛！一起騎行，同時自己決定速度和停留的時刻。這是 Coconara 最多人選擇的車款。",
    "cocoNote": "請先確認駕駛執照及租用條件，並按照現場職員指導充分練習後再出發。",
    "famiLead": "三款車中操作最容易的一款，推薦給不太熟悉駕駛的兩位旅客。",
    "famiBody": "車頂和擋板有助減少日曬及風吹。如果你想減少迎面而來的風，少一點擔心髮型和妝容，就舒適地遊覽牛島吧。",
    "openLead": "推薦給有駕駛綿羊仔經驗的兩位旅客，享受開放式電動車之旅。",
    "openBody": "想沒有擋板阻隔，一起感受海風的日子。並肩而坐，欣賞牛島的風景吧。",
    "book": "立即預約 ↗",
    "cocoBook": "預約 Coco",
    "famiBook": "預約 Fami",
    "openBook": "預約開篷車",
    "iceTab": "牛島花生雪糕",
    "iceNavAria": "牛島花生雪糕 · Dalkom Ajae",
    "brandTitle": "更親近牛島，更自在地旅行。",
    "brandIntro": "Coconara 的起點，是希望與更多人分享這座島外小島——牛島的美麗。",
    "brandBody": "無論是覺得長時間步行吃力的旅客、帶孩子同行的家庭，還是伴侶和朋友。我們希望每個人都能以適合自己的方式認識牛島，按照自己的步調累積回憶。",
    "brandJourney": "乘着 Coconara 的車沿海而行，在 Dalkom Ajae 品嚐牛島的滋味，再到 Hundertwasser 與自然和藝術相遇。我們把交通、美食與休憩串連起來，帶來充實的牛島一天。",
    "brandWish": "讓孩子走出書本，以五感認識大自然；讓相愛的人留下長久的回憶。願暢遊牛島的喜悅，化作珍惜這座島嶼與自然的心意。",
    "journeyRide": "Coconara · 自在出遊",
    "journeyTaste": "Dalkom Ajae · 牛島滋味",
    "journeyArt": "Hundertwasser · 自然與藝術",
    "gpsLabel": "我的位置",
    "gpsEnable": "開啟我的位置",
    "gpsDisable": "關閉定位",
    "headingLabel": "移動方向",
    "headingHint": "移動時，箭嘴會顯示你的移動方向。",
    "rentalTab": "租車",
    "exhibitionTab": "展覽館",
    "dalkomDirections": "NAVER 地圖路線",
    "dalkomWeb": "不開啟 App 查看店舖位置"
  },
  "zh-TW": {
    "chooseTitle": "你想怎麼暢遊牛島？",
    "chooseIntro": "同行的人不同，旅行的步調也不同。選一輛適合你的車吧。",
    "cocoName": "Coco（單人座）",
    "famiName": "Fami（雙人座）",
    "openName": "敞篷車（雙人座）",
    "cocoBadge": "各自騎乘更自在",
    "famiBadge": "操作容易",
    "openBadge": "一起迎著海風",
    "cocoSub": "一起來，各自騎！",
    "famiSub": "輕鬆駕駛，兩人舒適同行",
    "openSub": "並肩而坐，迎著海風",
    "cocoLead": "容易上手，享受隨心騎乘的樂趣。騎上迷你機車，貼近牛島的自在。",
    "cocoBody": "如果你已熟悉騎腳踏車的平衡感，不妨試試 Coco。伴侶或朋友同行，都能一人一輛！一起騎乘，同時自己決定速度和停留的時刻。這是 Coconara 最多人選擇的車款。",
    "cocoNote": "請先確認駕照及租用條件，並依照現場人員指導充分練習後再出發。",
    "famiLead": "三款車中操作最容易的一款，推薦給不太熟悉駕駛的兩位旅客。",
    "famiBody": "車頂和擋板有助減少日曬及風吹。如果你想減少迎面而來的風，少一點擔心髮型和妝容，就舒適地遊覽牛島吧。",
    "openLead": "推薦給有騎乘速克達經驗的兩位旅客，享受開放式電動車之旅。",
    "openBody": "想沒有擋板阻隔，一起感受海風的日子。並肩而坐，欣賞牛島的風景吧。",
    "book": "立即預約 ↗",
    "cocoBook": "預約 Coco",
    "famiBook": "預約 Fami",
    "openBook": "預約敞篷車",
    "iceTab": "牛島花生冰淇淋",
    "iceNavAria": "牛島花生冰淇淋 · Dalkom Ajae",
    "brandTitle": "更親近牛島，更自在地旅行。",
    "brandIntro": "Coconara 的起點，是希望與更多人分享這座島外小島——牛島的美麗。",
    "brandBody": "無論是覺得長時間步行吃力的旅客、帶孩子同行的家庭，還是伴侶和朋友。我們希望每個人都能以適合自己的方式認識牛島，按照自己的步調累積回憶。",
    "brandJourney": "乘著 Coconara 的車沿海而行，在 Dalkom Ajae 品嚐牛島的滋味，再到 Hundertwasser 與自然和藝術相遇。我們把交通、美食與休憩串連起來，帶來充實的牛島一天。",
    "brandWish": "讓孩子走出書本，以五感認識大自然；讓相愛的人留下長久的回憶。願暢遊牛島的喜悅，化作珍惜這座島嶼與自然的心意。",
    "journeyRide": "Coconara · 自在出遊",
    "journeyTaste": "Dalkom Ajae · 牛島滋味",
    "journeyArt": "Hundertwasser · 自然與藝術",
    "gpsLabel": "我的位置",
    "gpsEnable": "開啟我的位置",
    "gpsDisable": "關閉定位",
    "headingLabel": "移動方向",
    "headingHint": "移動時，箭頭會顯示你的移動方向。",
    "rentalTab": "租車",
    "exhibitionTab": "展覽館",
    "dalkomDirections": "NAVER 地圖路線",
    "dalkomWeb": "不用 App 查看店家位置"
  },
  "ja": {
    "chooseTitle": "どんなふうに牛島を巡りたいですか？",
    "chooseIntro": "一緒に旅する人も、旅のペースも人それぞれ。自分に合う一台を選んでみてください。",
    "cocoName": "ココ（1人乗り）",
    "famiName": "ファミ（2人乗り）",
    "openName": "オープンカー（2人乗り）",
    "cocoBadge": "一人一台の自由",
    "famiBadge": "操作が簡単",
    "openBadge": "二人で感じる海風",
    "cocoSub": "一緒に来ても、運転はそれぞれ！",
    "famiSub": "運転は気軽に、二人で快適に",
    "openSub": "隣に座って、海風の中へ",
    "cocoLead": "操作を覚えやすく、自分のペースで走る楽しさ。牛島の自由をいちばん身近に感じられるミニバイクです。",
    "cocoBody": "自転車でバランスを取る感覚に慣れている方は、ココに挑戦してみてください。恋人同士でも友人同士でも、一人一台！一緒に走りながらも、速さや立ち止まるタイミングは自分で決められます。ココナラで最も多く選ばれている車種です。",
    "cocoNote": "運転免許と利用条件を確認し、現地スタッフの案内に従って十分に練習してから出発してください。",
    "famiLead": "3車種の中で最も操作しやすく、運転にあまり慣れていないお二人におすすめです。",
    "famiBody": "屋根と風よけが日差しや風を和らげます。顔に当たる風や、髪型・メイクの崩れが気になる日は、快適に牛島を巡ってみてください。",
    "openLead": "スクーターの運転経験があるお二人におすすめの、開放感のある電気自動車です。",
    "openBody": "風よけなしで、海風を一緒に感じたい日に。隣同士に座って、牛島の景色を楽しんでみてください。",
    "book": "予約する ↗",
    "cocoBook": "ココを予約する",
    "famiBook": "ファミを予約する",
    "openBook": "オープンカーを予約する",
    "iceTab": "牛島ピーナッツアイス",
    "iceNavAria": "牛島のピーナッツアイス · ダルコムアジェ",
    "brandTitle": "牛島をもっと身近に、旅をもっと自由に。",
    "brandIntro": "ココナラは、島の中の島、牛島の美しさをもっと多くの方と分かち合いたいという思いから始まりました。",
    "brandBody": "長く歩く旅が大変な方も、お子さま連れのご家族も、恋人同士や友人同士も。それぞれに合う方法で牛島に出会い、自分のペースで思い出を重ねていただきたいと願っています。",
    "brandJourney": "ココナラで海沿いを走り、ダルコムアジェで牛島の味を楽しみ、フンデルトヴァッサーで自然と芸術に出会う一日。移動、おいしさ、ひと休みがつながる牛島の旅をお届けします。",
    "brandWish": "子どもたちには、本の外にある自然を五感で感じる時間を。大切な人たちには、いつまでも残る思い出を。牛島を楽しむ気持ちが、この島と自然を大切にする心につながることを願っています。",
    "journeyRide": "ココナラ · 自由に巡る",
    "journeyTaste": "ダルコムアジェ · 牛島の味",
    "journeyArt": "フンデルトヴァッサー · 自然と芸術",
    "gpsLabel": "現在地",
    "gpsEnable": "現在地を表示",
    "gpsDisable": "現在地をオフ",
    "headingLabel": "移動方向",
    "headingHint": "移動中は、矢印で進んでいる方向をお知らせします。",
    "rentalTab": "レンタル",
    "exhibitionTab": "展示館",
    "dalkomDirections": "NAVERマップで経路検索",
    "dalkomWeb": "アプリなしで店舗の場所を見る"
  }
}
;
