window.COCO_CHOICE_COPY={
  "ko": {
    "chooseTitle": "어떤 우도를 달리고 싶으세요?",
    "chooseIntro": "함께 온 사람도, 여행의 속도도 다르니까. 나에게 맞는 한 대를 골라보세요.",
    "cocoName": "코코 (1인승)",
    "famiName": "파미 (2인승)",
    "openName": "오픈카 (2인승)",
    "cocoBadge": "각자 타는 자유",
    "famiBadge": "안정적이고 쾌적한 승차감",
    "openBadge": "함께 맞는 바람",
    "cocoSub": "한 사람에 한 대씩, 함께 타요",
    "famiSub": "둘이 편하게 타는 2인승",
    "openSub": "바닷바람을 느끼는 2인승",
    "cocoLead": "가볍게 타고 다니기 좋은 1인승 스쿠터",
    "cocoBody": "자전거 타는 게 익숙한 분께 추천해요. 커플이나 친구끼리 오셨다면 한 대씩 타고 함께 둘러보세요. 코코나라에서 가장 많이 찾는 차종이에요.",
    "cocoNote": "운전면허와 이용 기준을 확인하고, 현장 안내에 따라 충분히 연습한 뒤 출발해 주세요.",
    "famiLead": "조작이 간편한 2인승을 찾으시면 파미를 추천해요.",
    "famiBody": "세 차종 중 조작이 가장 쉬운 차량이에요. 지붕과 가림막이 햇빛과 바람을 줄여줘요. 얼굴에 직접 닿는 바람이나 머리 헝클어짐이 신경 쓰이는 분께 잘 맞아요.",
    "openLead": "스쿠터를 타본 두 분께 추천하는 2인승 오픈카",
    "openBody": "가림막 없이 바닷바람을 그대로 느낄 수 있어요. 두 분이 나란히 앉아 해안도로를 달리고 싶다면 오픈카를 골라보세요.",
    "book": "예약하기 ↗",
    "cocoBook": "코코 예약하기",
    "famiBook": "파미 예약하기",
    "openBook": "오픈카 예약하기",
    "iceTab": "우도땅콩 아이스크림",
    "iceNavAria": "우도 땅콩아이스크림 · 달콤아재",
    "brandTitle": "코코나라 하나로, 우도 핵심 코스와 혜택을 한 번에.",
    "brandIntro": "코코나라 사장입니다. 차량만 빌려드리는 데서 끝내지 않겠습니다. 이동, 우도땅콩 아이스크림, 예술 테마파크, 오션뷰 카페까지. 우도에서 필요한 선택과 할인 혜택을 함께 준비했습니다.",
    "brandBody": "환승연애 시즌3·체인지데이즈 시즌2에 소개된 코코나라. 정가로 투명하게 운영하고, 매일 아침과 저녁 차량을 세척·점검합니다. 정해진 반납 마감까지 시간에 쫓기지 않고 이용하세요.",
    "brandJourney": "코코나라 예약 고객에게는 세 곳의 20% 할인 혜택까지. 우도 여행을 따로따로 찾을 필요 없이, 여기서 한 번에 확인하세요.",
    "brandWish": "대여의 기준은 코코나라. 우도를 즐기는 혜택도 코코나라. 제휴 할인 비용은 코코나라가 전액 부담합니다.",
    "journeyRide": "코코나라 · 자유로운 이동",
    "journeyTaste": "우도 달콤아재",
    "journeyArt": "훈데르트 바서파크",
    "gpsLabel": "내 위치",
    "gpsEnable": "내 위치 켜기",
    "gpsDisable": "내 위치 끄기",
    "headingLabel": "이동 방향",
    "headingHint": "이동 중에는 화살표로 이동 방향을 알려드려요.",
    "rentalTab": "대여장비",
    "exhibitionTab": "우도 예술 테마파크",
    "dalkomDirections": "네이버 지도 길찾기",
    "dalkomWeb": "앱 없이 매장 위치 보기",
    "iceOfferAria": "코코나라 예약 고객 쿠폰 20% 할인",
    "directionsTitle": "하우목동항 → 코코나라",
    "directionsSub": "항구에서 도보 1분 · 매장 찾아오기",
    "directionsPanel": "하우목동항에서 코코나라까지",
    "closePopup": "팝업 닫기",
    "harborContacts": "항구 대합실 연락처",
    "eligibilityTitle": "운전·대여 기본 조건",
    "eligibilityLicense": "2종 보통 이상 운전면허",
    "eligibilityAge": "만 21세 이상",
    "eligibilityNote": "두 조건을 모두 충족해야 합니다. 추가 이용 제한은 아래 안내를 확인해 주세요.",
    "eligibilityMore": "이용 불가 안내 확인 ↓",
    "couponPickup": "쿠폰 수령 장소",
    "couponCounter": "코코나라 매장 카운터",
    "couponCustomer": "예약 고객 전용 달콤아재 할인 쿠폰입니다. 코코나라 매장 카운터에서 받아가세요.",
    "couponRecommend": "우도에 왔다면, 한 컵에도 우도의 맛을. 우도땅콩으로 베이스부터 직접 만드는 달콤아재의 수제 아이스크림을 즐겨보세요.",
    "couponFunding": "달콤아재 할인금액은",
    "portSungsan": "성산항 대합실",
    "portHaumok": "하우목동항 대합실",
    "mapGuide": "지도 설명",
    "harborStatement": "코코나라는 “하우목동항”에 있습니다.",
    "harborBoarding": "승선할 때 하우목동항행인지 확인해 주세요. 배가 차면 일찍 출발할 수 있으니 미리 탑승해 주세요.",
    "broadcastTab": "방송출연",
    "broadcastIntro": "방송에서 만난 코코나라와 우도의 여행지",
    "broadcastCoco": "🛵 코코나라",
    "broadcastDalkom": "🍦 달콤아재",
    "broadcastPark": "🎨 훈데르트 바서파크",
    "recommendHello": "코코나라 사장입니다.",
    "recommendLead": "우도땅콩 아이스크림 독보적 1위, 달콤아재와 단독 협약을 맺었습니다.",
    "recommendTaste": "우도 현지 아이스크림 맛집을 묻는다면, 제 첫 번째 추천은 달콤아재입니다. 추천 기준은 명확합니다. 땅콩을 다루는 방식부터 아이스크림 한 컵의 구성이 다릅니다.",
    "recommendExperience": "하고수동 해수욕장 앞에서 약 10년간 이어온 우도 로컬 전문점. 우도 명물 한 컵을 고른다면, 베이스부터 토핑까지 직접 만드는 곳에서 드세요. 코코나라 예약 고객은 전 품목 20% 할인까지 받습니다.",
    "recommendMoment": "우도땅콩을 먹으러 왔다면, 달콤아재로 가세요.",
    "souvenirShort": "직접 만든 우도 마그넷도 만나보세요. 아이스크림과 함께 전 품목 20% 쿠폰 할인이 적용됩니다.",
    "parkFullTitle": "훈데르트 바서파크 & 훈데르트 윈즈카페",
    "parkStoryTitle": "바다를 달린 뒤, 예술 속을 걸어요.",
    "parkStoryIntro": "색색의 건물과 굽이치는 길, 그 사이로 자라는 나무들. 훈데르트바서의 예술을 따라 산책하고, 바다가 보이는 카페에서 잠시 쉬어가는 우도의 오후를 만나보세요.",
    "parkArtTitle": "그림에서 시작하는 산책",
    "parkArtBody": "회화·판화·생애·환경건축·파크, 다섯 전시관에서 예술가의 시선을 만나보세요.",
    "parkPhotoTitle": "사진으로 남기는 색채",
    "parkPhotoBody": "알록달록한 건물과 이국적인 조형물 사이, 걷는 곳마다 여행 사진이 됩니다.",
    "parkNatureTitle": "자연과 나란히",
    "parkNatureBody": "나무와 곡선이 어우러진 길을 천천히 걸으며 자연을 품은 건축을 느껴보세요.",
    "parkCafeTitle": "바다 앞에서 쉬어가기",
    "parkCafeBody": "훈데르트 윈즈카페에서 성산일출봉과 우도 바다를 바라보며 시그니처 우도넛을 즐겨보세요.",
    "parkTravel": "🕐 코코나라에서 약 40분",
    "parkHours": "09:30–18:00 · 매표 마감 17:00 · 연중무휴",
    "brandProofBroadcast": "방송이 담은 코코나라",
    "brandProofPrice": "투명한 정가 운영",
    "brandProofCare": "하루 2회 세척·점검",
    "brandProofTime": "반납 마감까지 여유롭게",
    "journeyTasteBenefit": "아이스크림·마그넷 전 품목 할인",
    "journeyArtBenefit": "예술 테마파크 입장료 할인",
    "journeyCafe": "훈데르트 윈즈카페",
    "journeyCafeBenefit": "성산일출봉 오션뷰·음료 할인",
    "tasteBaseTitle": "베이스부터 우도땅콩",
    "tasteBaseBody": "직접 로스팅한 우도 통땅콩을 갈아 베이스에 넣습니다. 첫입부터 진한 고소함이 나는 이유입니다.",
    "tasteRoastTitle": "그날 쓸 만큼, 매일 로스팅",
    "tasteRoastBody": "직접 농사짓고 수확·선별한 땅콩. 매일 필요한 양을 로스팅해 고소한 향과 식감을 살립니다.",
    "tasteToppingTitle": "토핑까지 직접 만드는 전문점",
    "tasteToppingBody": "수제 땅콩소스에 버무려 구운 아몬드, 땅콩 뻥과자, 직접 구운 ‘안녕우도’ 쿠키까지. 한 컵을 끝까지 고소하고 바삭하게 완성합니다.",
    "broadcastCafe": "☕ 훈데르트 윈즈카페",
    "ferryBubble": "코코나라는 하우목동항!",
    "fundingFocus": "코코나라가 전액 부담합니다.",
    "batteryBefore": "코코나라 신형 차량은 우도 한 바퀴를 기준으로 설계되어 있으며, 최대 2바퀴까지 주행이 가능합니다. 다만 운전 습관에 따라 배터리 소모량이 다를 수 있어,",
    "batteryLead": "여유롭고 안전한 관광을 위해",
    "batteryRange": "1.5바퀴 기준",
    "batteryAfter": "으로 이용하시길 권장드립니다.",
    "batteryFine": "※ 배터리 방전 시 견인 비용 발생 · 코코나라는 시간 제한 없이 여유롭게 이용 가능!",
    "portSeongsan": "성산항",
    "portHaumokdong": "하우목동항",
    "routeEntering": "우도 들어가실 때",
    "routeLeaving": "우도 나오실 때",
    "nextSailing": "다음 배 출항 시간",
    "sailingInfo": "운항 안내"
  },
  "en": {
    "chooseTitle": "How would you like to explore Udo?",
    "chooseIntro": "Different company, different pace. Find the ride that suits your trip.",
    "cocoName": "Coco (1 seat)",
    "famiName": "Fami (2 seats)",
    "openName": "Open-top (2 seats)",
    "cocoBadge": "Your own ride",
    "famiBadge": "Stable, comfortable ride",
    "openBadge": "Share the sea breeze",
    "cocoSub": "One scooter each, ride together",
    "famiSub": "Comfortable seating for two",
    "openSub": "An open ride for two",
    "cocoLead": "A handy one-seat scooter for exploring Udo",
    "cocoBody": "Recommended if you are comfortable riding a bicycle. Visiting as a couple or with friends? Rent one each and explore together. This is Coconara’s most popular model.",
    "cocoNote": "Check the driving licence and rental requirements, and practise thoroughly with the staff’s guidance before setting off.",
    "famiLead": "For an easy-to-operate two-seater, choose Fami.",
    "famiBody": "The easiest of our three models to operate. Its roof and screens reduce sun and wind exposure—a good fit if wind on your face or tousled hair bothers you.",
    "openLead": "A two-seat open-top vehicle for experienced scooter riders",
    "openBody": "Feel the sea breeze without side screens. Choose the open-top model if you want to sit side by side on a coastal drive.",
    "book": "Book now ↗",
    "cocoBook": "Book Coco",
    "famiBook": "Book Fami",
    "openBook": "Book Open-top",
    "iceTab": "Udo peanut ice cream",
    "iceNavAria": "Udo peanut ice cream · Dalkom Ajae",
    "brandTitle": "One Coconara booking. Udo’s key stops and benefits.",
    "brandIntro": "I’m the owner of Coconara. We offer more than a rental: transport, Udo peanut ice cream, an art theme park and an ocean-view café, with partner discounts in one place.",
    "brandBody": "Coconara featured in EXchange Season 3 and Change Days Season 2. We operate with transparent fixed prices and clean and inspect vehicles every morning and evening. Enjoy your rental until the stated return deadline.",
    "brandJourney": "Reservation customers also receive 20% discounts at three partner venues. Find your Udo route and its benefits together here.",
    "brandWish": "Coconara for your rental. Coconara for your Udo benefits. We cover the full cost of these partner discounts.",
    "journeyRide": "Coconara · Freedom to explore",
    "journeyTaste": "Dalkom Ajae",
    "journeyArt": "Hundertwasser Park",
    "gpsLabel": "My location",
    "gpsEnable": "Show my location",
    "gpsDisable": "Turn location off",
    "headingLabel": "Direction of travel",
    "headingHint": "While you move, an arrow shows your direction of travel.",
    "rentalTab": "Rentals",
    "exhibitionTab": "Udo Art Theme Park",
    "dalkomDirections": "Directions in NAVER Maps",
    "dalkomWeb": "View the shop without the app",
    "iceOfferAria": "20% off with a Coconara reservation coupon",
    "directionsTitle": "Haumokdong → Coconara",
    "directionsSub": "1-minute walk from the port · Find the shop",
    "directionsPanel": "From Haumokdong Port to Coconara",
    "closePopup": "Close popup",
    "harborContacts": "Ferry terminal contacts",
    "eligibilityTitle": "Basic rental requirements",
    "eligibilityLicense": "Korean Class 2 ordinary licence or higher",
    "eligibilityAge": "Age 21 or older",
    "eligibilityNote": "Both conditions are required. Please check the additional restrictions below.",
    "eligibilityMore": "Check rental restrictions ↓",
    "couponPickup": "Coupon pickup",
    "couponCounter": "Coconara shop counter",
    "couponCustomer": "A Dalkom Ajae coupon for reservation customers. Pick yours up at the Coconara shop counter.",
    "couponRecommend": "A taste of Udo in every cup. Enjoy Dalkom Ajae’s handmade ice cream, with a base made in-house using Udo peanuts.",
    "couponFunding": "Your Dalkom Ajae discount:",
    "portSungsan": "Seongsan Port terminal",
    "portHaumok": "Haumokdong Port terminal",
    "mapGuide": "Map guide",
    "harborStatement": "Coconara is at Haumokdong Port.",
    "harborBoarding": "Check that your ferry is bound for Haumokdong before boarding. Board early, as a full ferry may depart ahead of schedule.",
    "broadcastTab": "On TV",
    "broadcastIntro": "Coconara and Udo destinations featured on screen",
    "broadcastCoco": "🛵 Coconara",
    "broadcastDalkom": "🍦 Dalkom Ajae",
    "broadcastPark": "🎨 Hundertwasser Park",
    "recommendHello": "I’m the owner of Coconara.",
    "recommendLead": "We have an exclusive partnership with Dalkom Ajae, the undisputed No. 1 in Udo peanut ice cream.",
    "recommendTaste": "Asked for a local ice cream recommendation, my first choice is Dalkom Ajae. The reason is specific: how they handle the peanuts and build every cup.",
    "recommendExperience": "A local specialist by Hagosudong Beach for around ten years. For Udo’s signature treat, choose a shop that makes both the base and toppings. Coconara reservation customers get 20% off all items.",
    "recommendMoment": "Here for Udo peanuts? Make it Dalkom Ajae.",
    "souvenirShort": "Discover handmade Udo magnets too. The 20% coupon applies to all items, including ice cream and magnets.",
    "parkFullTitle": "Hundertwasser Park & Hundert Winds Café",
    "parkStoryTitle": "After the coastal drive, take a walk through art.",
    "parkStoryIntro": "Colourful buildings, winding paths and trees growing between them. Explore Hundertwasser’s art, then pause at a café overlooking the sea for a relaxed Udo afternoon.",
    "parkArtTitle": "A walk that begins with art",
    "parkArtBody": "Explore five exhibition spaces covering painting, prints, the artist’s life, environmental architecture and the park.",
    "parkPhotoTitle": "Colour worth capturing",
    "parkPhotoBody": "Bright buildings and distinctive sculptures turn each part of your walk into a holiday photo.",
    "parkNatureTitle": "Alongside nature",
    "parkNatureBody": "Follow paths where trees and curves meet, and discover architecture that embraces nature.",
    "parkCafeTitle": "A break by the sea",
    "parkCafeBody": "Enjoy views of Seongsan Ilchulbong and the Udo sea with a signature U-Donut at Hundert Winds Café.",
    "parkTravel": "🕐 About 40 minutes from Coconara",
    "parkHours": "09:30–18:00 · Last admission 17:00 · Open daily",
    "brandProofBroadcast": "Featured on TV",
    "brandProofPrice": "Transparent fixed prices",
    "brandProofCare": "Cleaned and checked twice daily",
    "brandProofTime": "Use until the return deadline",
    "journeyTasteBenefit": "All ice cream and magnets discounted",
    "journeyArtBenefit": "Art theme park admission discount",
    "journeyCafe": "Hundert Winds Café",
    "journeyCafeBenefit": "Ocean views and a drinks discount",
    "tasteBaseTitle": "Udo peanuts in the base",
    "tasteBaseBody": "Whole Udo peanuts are roasted in-house and ground into the ice cream base, giving it a rich, nutty flavour from the first bite.",
    "tasteRoastTitle": "Roasted daily, in the quantity needed",
    "tasteRoastBody": "They grow, harvest and select the peanuts themselves, then roast each day’s quantity to preserve the aroma and texture.",
    "tasteToppingTitle": "Handmade right through to the toppings",
    "tasteToppingBody": "Almonds baked with homemade peanut sauce, peanut puff crackers and handmade “Hello Udo” cookies complete a rich, crunchy cup.",
    "broadcastCafe": "☕ Hundert Winds Café",
    "ferryBubble": "Coconara: Haumokdong Port!",
    "fundingFocus": "Fully covered by Coconara.",
    "batteryBefore": "Our newer vehicles are designed for one circuit of Udo and can travel up to two circuits. Battery use varies with driving habits.",
    "batteryLead": "For a relaxed, safe visit, we recommend",
    "batteryRange": "1.5 circuits",
    "batteryAfter": " as your planned distance.",
    "batteryFine": "Towing fees apply if the battery runs out. Enjoy your rental without hourly limits.",
    "portSeongsan": "Seongsan",
    "portHaumokdong": "Haumokdong",
    "routeEntering": "When entering Udo",
    "routeLeaving": "When leaving Udo",
    "nextSailing": "Next ferry departure",
    "sailingInfo": "Service information"
  },
  "ms": {
    "chooseTitle": "Bagaimana anda ingin menerokai Udo?",
    "chooseIntro": "Teman perjalanan dan rentak percutian setiap orang berbeza. Pilih kenderaan yang sesuai untuk anda.",
    "cocoName": "Coco (1 tempat duduk)",
    "famiName": "Fami (2 tempat duduk)",
    "openName": "Kereta terbuka (2 tempat duduk)",
    "cocoBadge": "Bebas menunggang sendiri",
    "famiBadge": "Stabil dan selesa",
    "openBadge": "Nikmati bayu bersama",
    "cocoSub": "Satu skuter seorang, jalan bersama",
    "famiSub": "Selesa untuk dua orang",
    "openSub": "Nikmati angin laut berdua",
    "cocoLead": "Skuter satu tempat duduk untuk meneroka Udo",
    "cocoBody": "Disyorkan jika anda selesa menunggang basikal. Datang bersama pasangan atau rakan? Sewa satu seorang dan teroka bersama. Inilah model paling popular di Coconara.",
    "cocoNote": "Semak syarat lesen memandu dan penggunaan, kemudian berlatih secukupnya mengikut panduan petugas sebelum bertolak.",
    "famiLead": "Untuk dua tempat duduk yang mudah dikendalikan, pilih Fami.",
    "famiBody": "Paling mudah dikendalikan antara tiga model kami. Bumbung dan penghadang mengurangkan cahaya matahari serta angin, sesuai jika angin pada muka atau rambut kusut mengganggu anda.",
    "openLead": "Kenderaan terbuka dua tempat duduk untuk penunggang skuter berpengalaman",
    "openBody": "Rasai angin laut tanpa penghadang sisi. Pilih model terbuka untuk duduk bersebelahan sepanjang perjalanan pesisir.",
    "book": "Tempah sekarang ↗",
    "cocoBook": "Tempah Coco",
    "famiBook": "Tempah Fami",
    "openBook": "Tempah kereta terbuka",
    "iceTab": "Aiskrim kacang Udo",
    "iceNavAria": "Aiskrim kacang tanah Udo · Dalkom Ajae",
    "brandTitle": "Satu tempahan Coconara. Destinasi utama dan manfaat Udo.",
    "brandIntro": "Saya pemilik Coconara. Kami menyediakan lebih daripada sewaan: pengangkutan, aiskrim kacang Udo, taman tema seni dan kafe pemandangan laut, bersama diskaun rakan niaga.",
    "brandBody": "Coconara ditampilkan dalam EXchange Musim 3 dan Change Days Musim 2. Harga tetap dan telus; kenderaan dicuci serta diperiksa setiap pagi dan petang. Gunakan sehingga waktu akhir pemulangan yang ditetapkan.",
    "brandJourney": "Pelanggan tempahan turut mendapat diskaun 20% di tiga destinasi rakan niaga. Semak laluan Udo dan manfaatnya di satu tempat.",
    "brandWish": "Coconara untuk sewaan dan manfaat perjalanan Udo anda. Kos penuh diskaun rakan niaga ditanggung oleh Coconara.",
    "journeyRide": "Coconara · Bebas meneroka",
    "journeyTaste": "Dalkom Ajae",
    "journeyArt": "Taman Hundertwasser",
    "gpsLabel": "Lokasi saya",
    "gpsEnable": "Tunjukkan lokasi saya",
    "gpsDisable": "Matikan lokasi",
    "headingLabel": "Arah pergerakan",
    "headingHint": "Semasa anda bergerak, anak panah menunjukkan arah pergerakan anda.",
    "rentalTab": "Sewaan",
    "exhibitionTab": "Taman Seni Udo",
    "dalkomDirections": "Arah di NAVER Maps",
    "dalkomWeb": "Lihat lokasi kedai tanpa aplikasi",
    "iceOfferAria": "Diskaun 20% dengan kupon tempahan Coconara",
    "directionsTitle": "Haumokdong → Coconara",
    "directionsSub": "Berjalan 1 minit dari pelabuhan · Cari kedai",
    "directionsPanel": "Dari Pelabuhan Haumokdong ke Coconara",
    "closePopup": "Tutup tetingkap",
    "harborContacts": "Hubungi terminal feri",
    "eligibilityTitle": "Syarat asas sewaan",
    "eligibilityLicense": "Lesen biasa Korea Kelas 2 atau lebih tinggi",
    "eligibilityAge": "Berumur 21 tahun ke atas",
    "eligibilityNote": "Kedua-dua syarat diperlukan. Semak sekatan tambahan di bawah.",
    "eligibilityMore": "Semak sekatan sewaan ↓",
    "couponPickup": "Tempat ambil kupon",
    "couponCounter": "Kaunter kedai Coconara",
    "couponCustomer": "Kupon Dalkom Ajae untuk pelanggan tempahan. Ambil di kaunter kedai Coconara.",
    "couponRecommend": "Rasa Udo dalam setiap cawan. Nikmati aiskrim buatan tangan Dalkom Ajae, dengan asas yang dibuat sendiri menggunakan kacang Udo.",
    "couponFunding": "Diskaun Dalkom Ajae anda:",
    "portSungsan": "Terminal Pelabuhan Seongsan",
    "portHaumok": "Terminal Pelabuhan Haumokdong",
    "mapGuide": "Panduan peta",
    "harborStatement": "Coconara terletak di Pelabuhan Haumokdong.",
    "harborBoarding": "Pastikan feri menuju ke Haumokdong sebelum menaiki feri. Naik awal kerana feri yang penuh mungkin bertolak lebih awal.",
    "broadcastTab": "Di TV",
    "broadcastIntro": "Coconara dan destinasi Udo yang dipaparkan di layar",
    "broadcastCoco": "🛵 Coconara",
    "broadcastDalkom": "🍦 Dalkom Ajae",
    "broadcastPark": "🎨 Taman Hundertwasser",
    "recommendHello": "Saya pemilik Coconara.",
    "recommendLead": "Kami menjalin kerjasama eksklusif dengan Dalkom Ajae, peneraju No. 1 aiskrim kacang tanah Udo.",
    "recommendTaste": "Untuk aiskrim tempatan Udo, pilihan pertama saya ialah Dalkom Ajae. Sebabnya jelas: cara kacang diproses dan setiap cawan disediakan.",
    "recommendExperience": "Pakar tempatan di hadapan Pantai Hagosudong selama kira-kira sepuluh tahun. Untuk hidangan ikonik Udo, pilih kedai yang membuat asas dan topping sendiri. Pelanggan tempahan Coconara menikmati diskaun 20% semua barangan.",
    "recommendMoment": "Datang untuk kacang Udo? Singgah di Dalkom Ajae.",
    "souvenirShort": "Lihat juga magnet Udo buatan tangan. Kupon diskaun 20% boleh digunakan untuk semua barangan, termasuk aiskrim dan magnet.",
    "parkFullTitle": "Taman Hundertwasser & Kafe Hundert Winds",
    "parkStoryTitle": "Selepas menyusuri pantai, berjalanlah dalam dunia seni.",
    "parkStoryIntro": "Bangunan berwarna-warni, laluan berliku dan pokok di antaranya. Terokai seni Hundertwasser, kemudian berehat di kafe menghadap laut pada petang yang santai di Udo.",
    "parkArtTitle": "Bermula dengan seni",
    "parkArtBody": "Lima ruang pameran memperkenalkan lukisan, cetakan, kehidupan artis, seni bina alam sekitar dan taman.",
    "parkPhotoTitle": "Warna untuk dirakam",
    "parkPhotoBody": "Bangunan ceria dan arca unik menjadikan setiap sudut tempat yang indah untuk gambar percutian.",
    "parkNatureTitle": "Bersama alam",
    "parkNatureBody": "Susuri laluan dengan pepohon dan lengkungan, sambil menikmati seni bina yang menyatu dengan alam.",
    "parkCafeTitle": "Berehat di tepi laut",
    "parkCafeBody": "Nikmati pemandangan Seongsan Ilchulbong dan laut Udo bersama U-Donut istimewa di Kafe Hundert Winds.",
    "parkTravel": "🕐 Kira-kira 40 minit dari Coconara",
    "parkHours": "09:30–18:00 · Kemasukan terakhir 17:00 · Dibuka setiap hari",
    "brandProofBroadcast": "Ditampilkan di TV",
    "brandProofPrice": "Harga tetap dan telus",
    "brandProofCare": "Cuci dan periksa dua kali sehari",
    "brandProofTime": "Guna hingga waktu pemulangan",
    "journeyTasteBenefit": "Diskaun semua aiskrim dan magnet",
    "journeyArtBenefit": "Diskaun tiket taman tema seni",
    "journeyCafe": "Kafe Hundert Winds",
    "journeyCafeBenefit": "Pemandangan laut dan diskaun minuman",
    "tasteBaseTitle": "Kacang Udo dalam asas aiskrim",
    "tasteBaseBody": "Kacang Udo dipanggang sendiri dan dikisar ke dalam asas aiskrim untuk rasa kacang yang kaya sejak suapan pertama.",
    "tasteRoastTitle": "Dipanggang segar setiap hari",
    "tasteRoastBody": "Kacang ditanam, dituai dan dipilih sendiri. Hanya jumlah yang diperlukan pada hari itu dipanggang bagi mengekalkan aroma dan tekstur.",
    "tasteToppingTitle": "Topping juga buatan tangan",
    "tasteToppingBody": "Badam dibakar dengan sos kacang buatan sendiri, keropok kacang dan biskut “Hello Udo” melengkapkan setiap cawan dengan rasa kaya dan rangup.",
    "broadcastCafe": "☕ Kafe Hundert Winds",
    "ferryBubble": "Coconara: Pelabuhan Haumokdong!",
    "fundingFocus": "Ditanggung sepenuhnya oleh Coconara.",
    "batteryBefore": "Kenderaan baharu kami direka untuk satu pusingan Udo dan boleh bergerak sehingga dua pusingan. Penggunaan bateri bergantung pada cara memandu.",
    "batteryLead": "Untuk perjalanan yang santai dan selamat, kami syorkan",
    "batteryRange": "1.5 pusingan",
    "batteryAfter": " sebagai jarak yang dirancang.",
    "batteryFine": "Caj tunda dikenakan jika bateri habis. Sewaan tanpa had jam.",
    "portSeongsan": "Seongsan",
    "portHaumokdong": "Haumokdong",
    "routeEntering": "Ke Udo",
    "routeLeaving": "Dari Udo",
    "nextSailing": "Pelepasan feri seterusnya",
    "sailingInfo": "Maklumat perkhidmatan"
  },
  "zh-HK": {
    "chooseTitle": "你想怎樣暢遊牛島？",
    "chooseIntro": "同行的人不同，旅行的步調也不同。選一輛適合你的車吧。",
    "cocoName": "Coco（單人座）",
    "famiName": "Fami（雙人座）",
    "openName": "開篷車（雙人座）",
    "cocoBadge": "各自騎行更自在",
    "famiBadge": "平穩舒適的乘坐體驗",
    "openBadge": "一起迎着海風",
    "cocoSub": "一人一車，一起出發",
    "famiSub": "兩人舒適同行",
    "openSub": "兩人感受海風",
    "cocoLead": "輕巧的單人座電動車，輕鬆遊牛島",
    "cocoBody": "推薦給熟悉踩單車的旅客。情侶或朋友同行，可以各租一輛一起遊覽。這是 Coconara 最受歡迎的車款。",
    "cocoNote": "請先確認駕駛執照及租用條件，並按照現場職員指導充分練習後再出發。",
    "famiLead": "想選操作簡單的雙人車，推薦 Fami。",
    "famiBody": "三款車中最容易操作。車頂和擋風板可減少陽光與風吹，適合在意迎面風或髮型被吹亂的旅客。",
    "openLead": "推薦給有綿羊仔駕駛經驗的旅客",
    "openBody": "沒有側邊擋風板，可以直接感受海風。想兩人並排坐著遊海岸公路，可選開篷款。",
    "book": "立即預約 ↗",
    "cocoBook": "預約 Coco",
    "famiBook": "預約 Fami",
    "openBook": "預約開篷車",
    "iceTab": "牛島花生雪糕",
    "iceNavAria": "牛島花生雪糕 · Dalkom Ajae",
    "brandTitle": "預約 Coconara，牛島行程與優惠一次到位。",
    "brandIntro": "我是 Coconara 店主。我們提供的不只租車，更把交通、牛島花生雪糕、藝術主題公園及海景咖啡店，連同合作商戶優惠一起準備好。",
    "brandBody": "Coconara 曾亮相《換乘戀愛》第3季及《Change Days》第2季。我們採用透明定價，每天早晚清潔及檢查車輛，讓您安心使用至指定還車時間。",
    "brandJourney": "預約客人更可享三間合作商戶的八折優惠。牛島的重點行程與優惠，在這裏一次看清。",
    "brandWish": "租車選 Coconara，牛島優惠亦由 Coconara 準備。合作優惠的費用由我們全額承擔。",
    "journeyRide": "Coconara · 自在出遊",
    "journeyTaste": "Dalkom Ajae",
    "journeyArt": "百水藝術公園",
    "gpsLabel": "我的位置",
    "gpsEnable": "開啟我的位置",
    "gpsDisable": "關閉定位",
    "headingLabel": "移動方向",
    "headingHint": "移動時，箭嘴會顯示你的移動方向。",
    "rentalTab": "租車",
    "exhibitionTab": "牛島藝術主題公園",
    "dalkomDirections": "NAVER 地圖路線",
    "dalkomWeb": "不開啟 App 查看店舖位置",
    "iceOfferAria": "憑 Coconara 預約優惠券享八折",
    "directionsTitle": "下牛目洞港 → Coconara",
    "directionsSub": "由港口步行1分鐘 · 前往店舖",
    "directionsPanel": "由下牛目洞港前往 Coconara",
    "closePopup": "關閉視窗",
    "harborContacts": "碼頭候船室聯絡電話",
    "eligibilityTitle": "基本租用條件",
    "eligibilityLicense": "持韓國二種普通或以上駕駛執照",
    "eligibilityAge": "年滿21歲",
    "eligibilityNote": "須同時符合兩項條件，其他使用限制請參閱下方說明。",
    "eligibilityMore": "查看不可使用情況 ↓",
    "couponPickup": "優惠券領取地點",
    "couponCounter": "Coconara 店舖櫃檯",
    "couponCustomer": "預約顧客專享的 Dalkom Ajae 優惠券，請到 Coconara 店舖櫃檯領取。",
    "couponRecommend": "一杯雪糕，品味牛島。Dalkom Ajae 以牛島花生自製基底，帶來手工雪糕的香濃滋味。",
    "couponFunding": "Dalkom Ajae 的折扣金額，",
    "portSungsan": "城山港候船室",
    "portHaumok": "下牛目洞港候船室",
    "mapGuide": "地圖說明",
    "harborStatement": "Coconara 位於「下牛目洞港」。",
    "harborBoarding": "上船前請確認目的地是下牛目洞港。客滿的船可能提早開出，請預先登船。",
    "broadcastTab": "電視介紹",
    "broadcastIntro": "在節目中認識 Coconara 與牛島景點",
    "broadcastCoco": "🛵 Coconara",
    "broadcastDalkom": "🍦 Dalkom Ajae",
    "broadcastPark": "🎨 百水藝術公園",
    "recommendHello": "我是 Coconara 的老闆。",
    "recommendLead": "我們與牛島花生雪糕穩居第一的 Dalkom Ajae 簽訂了獨家合作協議。",
    "recommendTaste": "問我牛島哪間雪糕店值得去，首推 Dalkom Ajae。理由很實在：從花生處理方式到一杯雪糕的配搭，都有自己的做法。",
    "recommendExperience": "在下高水洞海灘前經營約十年的本地專門店。想試牛島名物，就選基底和配料都親手製作的店。Coconara 預約客人更享全品項八折。",
    "recommendMoment": "為牛島花生而來，就去 Dalkom Ajae。",
    "souvenirShort": "也可以看看手製牛島磁石。雪糕與磁石等全店商品均可使用八折優惠券。",
    "parkFullTitle": "百水藝術公園 & Hundert Winds 咖啡店",
    "parkStoryTitle": "沿海兜風之後，走進藝術風景。",
    "parkStoryIntro": "色彩繽紛的建築、蜿蜒的小路，還有其間生長的樹木。沿着百水先生的藝術世界散步，再到望海咖啡店歇一歇，享受牛島的午後。",
    "parkArtTitle": "從藝術開始散步",
    "parkArtBody": "在繪畫、版畫、生平、環境建築與公園五個展館，認識藝術家的視野。",
    "parkPhotoTitle": "把色彩留在照片裏",
    "parkPhotoBody": "明亮的建築與獨特的雕塑，讓散步的每一角都成為旅行照片。",
    "parkNatureTitle": "與自然同行",
    "parkNatureBody": "慢慢走過樹木與曲線交織的小路，感受擁抱自然的建築。",
    "parkCafeTitle": "在海邊歇一歇",
    "parkCafeBody": "在 Hundert Winds 咖啡店欣賞城山日出峰與牛島海景，品嚐招牌 U-Donut。",
    "parkTravel": "🕐 距離 Coconara 約 40 分鐘",
    "parkHours": "09:30–18:00 · 售票至 17:00 · 全年開放",
    "brandProofBroadcast": "電視節目取景",
    "brandProofPrice": "透明定價",
    "brandProofCare": "每日兩次清潔及檢查",
    "brandProofTime": "使用至指定還車時間",
    "journeyTasteBenefit": "雪糕及磁石全品項八折",
    "journeyArtBenefit": "藝術主題公園門票八折",
    "journeyCafe": "Hundert Winds Café",
    "journeyCafeBenefit": "城山日出峰海景・飲品八折",
    "tasteBaseTitle": "花生直接加入雪糕基底",
    "tasteBaseBody": "自行烘焙牛島整粒花生，再磨碎加入基底，第一口已經香濃。",
    "tasteRoastTitle": "每天只烘焙當天所需份量",
    "tasteRoastBody": "花生由自己種植、收成及挑選，每天按需烘焙，保留香氣與口感。",
    "tasteToppingTitle": "連配料也親手製作",
    "tasteToppingBody": "自製花生醬拌杏仁焗成配料，配上花生米通及手製「Hello Udo」曲奇，每一杯都香濃鬆脆。",
    "broadcastCafe": "☕ Hundert Winds Café",
    "ferryBubble": "Coconara 就在下牛目洞港！",
    "fundingFocus": "由 Coconara 全額承擔。",
    "batteryBefore": "新款車輛以環島一圈為設計基準，最多可行駛兩圈。電池耗電量會因駕駛習慣而異。",
    "batteryLead": "為了輕鬆、安全地遊覽，建議以",
    "batteryRange": "1.5圈",
    "batteryAfter": "為行程基準。",
    "batteryFine": "※ 電池耗盡須支付拖車費。Coconara 租車不設每小時時限。",
    "portSeongsan": "城山港",
    "portHaumokdong": "下牛目洞港",
    "routeEntering": "前往牛島",
    "routeLeaving": "離開牛島",
    "nextSailing": "下一班開船時間",
    "sailingInfo": "航班資訊"
  },
  "zh-TW": {
    "chooseTitle": "你想怎麼暢遊牛島？",
    "chooseIntro": "同行的人不同，旅行的步調也不同。選一輛適合你的車吧。",
    "cocoName": "Coco（單人座）",
    "famiName": "Fami（雙人座）",
    "openName": "敞篷車（雙人座）",
    "cocoBadge": "各自騎乘更自在",
    "famiBadge": "平穩舒適的乘坐體驗",
    "openBadge": "一起迎著海風",
    "cocoSub": "一人一車，一起出發",
    "famiSub": "兩人舒適同行",
    "openSub": "兩人感受海風",
    "cocoLead": "輕巧的單人座電動車，輕鬆遊牛島",
    "cocoBody": "推薦給熟悉騎腳踏車的旅客。情侶或朋友同行，可以各租一輛一起遊覽。這是 Coconara 最受歡迎的車款。",
    "cocoNote": "請先確認駕照及租用條件，並依照現場人員指導充分練習後再出發。",
    "famiLead": "想選操作簡單的雙人車，推薦 Fami。",
    "famiBody": "三款車中最容易操作。車頂和擋風板可減少陽光與風吹，適合在意迎面風或髮型被吹亂的旅客。",
    "openLead": "推薦給有速克達騎乘經驗的旅客",
    "openBody": "沒有側邊擋風板，可以直接感受海風。想兩人並排坐著遊海岸公路，可選敞篷款。",
    "book": "立即預約 ↗",
    "cocoBook": "預約 Coco",
    "famiBook": "預約 Fami",
    "openBook": "預約敞篷車",
    "iceTab": "牛島花生冰淇淋",
    "iceNavAria": "牛島花生冰淇淋 · Dalkom Ajae",
    "brandTitle": "預約 Coconara，牛島行程與優惠一次到位。",
    "brandIntro": "我是 Coconara 店主。我們提供的不只租車，更將交通、牛島花生冰淇淋、藝術主題公園及海景咖啡廳，連同合作店家優惠一起準備好。",
    "brandBody": "Coconara 曾出現在《換乘戀愛》第3季及《Change Days》第2季。我們採用透明定價，每天早晚清潔及檢查車輛，讓您安心使用至指定還車時間。",
    "brandJourney": "預約客人更可享三間合作店家的八折優惠。牛島的重點行程與優惠，在這裡一次看清。",
    "brandWish": "租車選 Coconara，牛島優惠也由 Coconara 準備。合作優惠的費用由我們全額負擔。",
    "journeyRide": "Coconara · 自在出遊",
    "journeyTaste": "Dalkom Ajae",
    "journeyArt": "百水藝術公園",
    "gpsLabel": "我的位置",
    "gpsEnable": "開啟我的位置",
    "gpsDisable": "關閉定位",
    "headingLabel": "移動方向",
    "headingHint": "移動時，箭頭會顯示你的移動方向。",
    "rentalTab": "租車",
    "exhibitionTab": "牛島藝術主題公園",
    "dalkomDirections": "NAVER 地圖路線",
    "dalkomWeb": "不用 App 查看店家位置",
    "iceOfferAria": "憑 Coconara 預約優惠券享八折",
    "directionsTitle": "下牛目洞港 → Coconara",
    "directionsSub": "從港口步行1分鐘 · 前往店家",
    "directionsPanel": "從下牛目洞港前往 Coconara",
    "closePopup": "關閉視窗",
    "harborContacts": "碼頭候船室聯絡電話",
    "eligibilityTitle": "基本租借條件",
    "eligibilityLicense": "持韓國二種普通或以上駕駛執照",
    "eligibilityAge": "年滿21歲",
    "eligibilityNote": "須同時符合兩項條件，其他使用限制請參閱下方說明。",
    "eligibilityMore": "查看不可使用情況 ↓",
    "couponPickup": "優惠券領取地點",
    "couponCounter": "Coconara 店內櫃檯",
    "couponCustomer": "預約顧客專享的 Dalkom Ajae 優惠券，請到 Coconara 店內櫃檯領取。",
    "couponRecommend": "一杯冰淇淋，品味牛島。Dalkom Ajae 以牛島花生自製基底，帶來手工冰淇淋的香濃滋味。",
    "couponFunding": "Dalkom Ajae 的折扣金額，",
    "portSungsan": "城山港候船室",
    "portHaumok": "下牛目洞港候船室",
    "mapGuide": "地圖說明",
    "harborStatement": "Coconara 位於「下牛目洞港」。",
    "harborBoarding": "登船前請確認目的地是下牛目洞港。客滿的船可能提早出發，請提前上船。",
    "broadcastTab": "電視介紹",
    "broadcastIntro": "在節目中認識 Coconara 與牛島景點",
    "broadcastCoco": "🛵 Coconara",
    "broadcastDalkom": "🍦 Dalkom Ajae",
    "broadcastPark": "🎨 百水藝術公園",
    "recommendHello": "我是 Coconara 的老闆。",
    "recommendLead": "我們與牛島花生冰淇淋穩居第一的 Dalkom Ajae 簽訂了獨家合作協議。",
    "recommendTaste": "問我牛島哪間冰淇淋店值得去，首推 Dalkom Ajae。理由很實在：從花生處理方式到一杯冰淇淋的搭配，都有自己的做法。",
    "recommendExperience": "在下高水洞海灘前經營約十年的在地專門店。想試牛島名物，就選基底和配料都親手製作的店。Coconara 預約客人更享全品項八折。",
    "recommendMoment": "為牛島花生而來，就去 Dalkom Ajae。",
    "souvenirShort": "也可以看看手作牛島磁鐵。冰淇淋與磁鐵等全店商品都能使用八折優惠券。",
    "parkFullTitle": "百水藝術公園 & Hundert Winds 咖啡廳",
    "parkStoryTitle": "沿海兜風之後，走進藝術風景。",
    "parkStoryIntro": "色彩繽紛的建築、蜿蜒的小路，還有其間生長的樹木。沿著百水先生的藝術世界散步，再到海景咖啡廳歇一歇，享受牛島的午後。",
    "parkArtTitle": "從藝術開始散步",
    "parkArtBody": "在繪畫、版畫、生平、環境建築與公園五個展館，認識藝術家的視野。",
    "parkPhotoTitle": "把色彩留在照片裡",
    "parkPhotoBody": "明亮的建築與獨特的雕塑，讓散步的每一角都成為旅行照片。",
    "parkNatureTitle": "與自然同行",
    "parkNatureBody": "慢慢走過樹木與曲線交織的小路，感受擁抱自然的建築。",
    "parkCafeTitle": "在海邊歇一歇",
    "parkCafeBody": "在 Hundert Winds 咖啡廳欣賞城山日出峰與牛島海景，品嚐招牌 U-Donut。",
    "parkTravel": "🕐 距離 Coconara 約 40 分鐘",
    "parkHours": "09:30–18:00 · 售票至 17:00 · 全年開放",
    "brandProofBroadcast": "電視節目取景",
    "brandProofPrice": "透明定價",
    "brandProofCare": "每日兩次清潔及檢查",
    "brandProofTime": "使用至指定還車時間",
    "journeyTasteBenefit": "冰淇淋及磁鐵全品項八折",
    "journeyArtBenefit": "藝術主題公園門票八折",
    "journeyCafe": "Hundert Winds Café",
    "journeyCafeBenefit": "城山日出峰海景・飲品八折",
    "tasteBaseTitle": "花生直接加入冰淇淋基底",
    "tasteBaseBody": "自行烘焙牛島整粒花生，再磨碎加入基底，第一口就香濃。",
    "tasteRoastTitle": "每天只烘焙當天所需份量",
    "tasteRoastBody": "花生由自己種植、收成及挑選，每天按需烘焙，保留香氣與口感。",
    "tasteToppingTitle": "連配料也親手製作",
    "tasteToppingBody": "自製花生醬拌杏仁烤成配料，配上花生米香及手製「Hello Udo」餅乾，每一杯都香濃酥脆。",
    "broadcastCafe": "☕ Hundert Winds Café",
    "ferryBubble": "Coconara 就在下牛目洞港！",
    "fundingFocus": "由 Coconara 全額負擔。",
    "batteryBefore": "新款車輛以環島一圈為設計基準，最多可行駛兩圈。電池耗電量會因駕駛習慣而異。",
    "batteryLead": "為了輕鬆、安全地遊覽，建議以",
    "batteryRange": "1.5圈",
    "batteryAfter": "為行程基準。",
    "batteryFine": "※ 電池耗盡須支付拖車費。Coconara 租車不設每小時時限。",
    "portSeongsan": "城山港",
    "portHaumokdong": "下牛目洞港",
    "routeEntering": "前往牛島",
    "routeLeaving": "離開牛島",
    "nextSailing": "下一班開船時間",
    "sailingInfo": "航班資訊"
  },
  "ja": {
    "chooseTitle": "どんなふうに牛島を巡りたいですか？",
    "chooseIntro": "一緒に旅する人も、旅のペースも人それぞれ。自分に合う一台を選んでみてください。",
    "cocoName": "ココ（1人乗り）",
    "famiName": "ファミ（2人乗り）",
    "openName": "オープンカー（2人乗り）",
    "cocoBadge": "一人一台の自由",
    "famiBadge": "安定した快適な乗り心地",
    "openBadge": "二人で感じる海風",
    "cocoSub": "1人1台で、一緒に出発",
    "famiSub": "2人で快適に",
    "openSub": "2人で海風を感じる",
    "cocoLead": "気軽に牛島を回れる1人乗りスクーター",
    "cocoBody": "自転車に乗り慣れている方におすすめ。カップルや友人同士なら1人1台ずつ借りて一緒に回れます。ココナラでいちばん人気の車種です。",
    "cocoNote": "運転免許と利用条件を確認し、現地スタッフの案内に従って十分に練習してから出発してください。",
    "famiLead": "操作しやすい2人乗りなら、ファミがおすすめ。",
    "famiBody": "3車種の中で最も操作しやすい車両です。屋根と風よけが日差しや風を軽減するので、顔に当たる風や髪の乱れが気になる方に向いています。",
    "openLead": "スクーター経験者におすすめの2人乗りオープンカー",
    "openBody": "横の風よけがなく、海風をそのまま感じられます。2人並んで海岸道路を走りたい方におすすめです。",
    "book": "予約する ↗",
    "cocoBook": "ココを予約する",
    "famiBook": "ファミを予約する",
    "openBook": "オープンカーを予約する",
    "iceTab": "牛島ピーナッツアイス",
    "iceNavAria": "牛島のピーナッツアイス · ダルコムアジェ",
    "brandTitle": "ココナラひとつで、牛島の定番コースと特典を。",
    "brandIntro": "ココナラの店主です。車両レンタルに加え、移動、牛島ピーナッツアイス、アートテーマパーク、オーシャンビューカフェまで。旅の選択肢と提携割引をまとめてご用意しました。",
    "brandBody": "「乗り換え恋愛」シーズン3と「Change Days」シーズン2に登場したココナラ。明瞭な定価で営業し、毎朝・毎夕に車両を清掃・点検。指定の返却締切までご利用いただけます。",
    "brandJourney": "予約のお客様は、提携3店舗で20%割引も。牛島の定番コースと特典をここでまとめて確認できます。",
    "brandWish": "レンタルも、牛島を楽しむ特典もココナラ。提携割引の費用はココナラが全額負担します。",
    "journeyRide": "ココナラ · 自由に巡る",
    "journeyTaste": "ダルコムアジェ",
    "journeyArt": "フンデルトヴァッサー・パーク",
    "gpsLabel": "現在地",
    "gpsEnable": "現在地を表示",
    "gpsDisable": "現在地をオフ",
    "headingLabel": "移動方向",
    "headingHint": "移動中は、矢印で進んでいる方向をお知らせします。",
    "rentalTab": "レンタル",
    "exhibitionTab": "牛島アートテーマパーク",
    "dalkomDirections": "NAVERマップで経路検索",
    "dalkomWeb": "アプリなしで店舗の場所を見る",
    "iceOfferAria": "ココナラ予約者クーポンで20%オフ",
    "directionsTitle": "下牛目洞港 → Coconara",
    "directionsSub": "港から徒歩1分 · お店への道順",
    "directionsPanel": "下牛目洞港からCoconaraへ",
    "closePopup": "閉じる",
    "harborContacts": "港の待合室への電話",
    "eligibilityTitle": "運転・レンタルの基本条件",
    "eligibilityLicense": "韓国の2種普通以上の運転免許",
    "eligibilityAge": "満21歳以上",
    "eligibilityNote": "両方の条件を満たす必要があります。その他の利用制限は下記をご確認ください。",
    "eligibilityMore": "利用できない条件を確認 ↓",
    "couponPickup": "クーポン受取場所",
    "couponCounter": "Coconara店内カウンター",
    "couponCustomer": "予約のお客様専用のDalkom Ajae割引クーポンです。Coconara店内カウンターでお受け取りください。",
    "couponRecommend": "一杯で味わう、牛島らしさ。牛島ピーナッツでベースから手作りするDalkom Ajaeのアイスクリームをお楽しみください。",
    "couponFunding": "ダルコムアジェの割引額は、",
    "portSungsan": "城山港 待合室",
    "portHaumok": "ハウモクドン港 待合室",
    "mapGuide": "地図の案内",
    "harborStatement": "Coconaraは「ハウモクドン港」にあります。",
    "harborBoarding": "乗船前にハウモクドン港行きか確認してください。満員になると早く出航する場合があるので、お早めにご乗船ください。",
    "broadcastTab": "テレビ紹介",
    "broadcastIntro": "番組に登場したCoconaraと牛島のスポット",
    "broadcastCoco": "🛵 Coconara",
    "broadcastDalkom": "🍦 Dalkom Ajae",
    "broadcastPark": "🎨 フンデルトヴァッサー・パーク",
    "recommendHello": "Coconaraの店主です。",
    "recommendLead": "牛島ピーナッツアイスクリームで圧倒的なNo.1、Dalkom Ajaeと独占提携を結びました。",
    "recommendTaste": "牛島のアイス店を聞かれたら、私が最初に薦めるのはダルコムアジェです。理由は明確。ピーナッツの扱いから一杯の組み立て方まで、こだわりがあります。",
    "recommendExperience": "下高水洞海水浴場前で約10年続く地元の専門店。牛島名物を味わうなら、ベースもトッピングも自ら作るお店へ。ココナラ予約のお客様は全商品20%割引です。",
    "recommendMoment": "牛島ピーナッツを食べに来たなら、ダルコムアジェへ。",
    "souvenirShort": "手作りの牛島マグネットもぜひ。アイスやマグネットを含む全商品に20%割引クーポンが使えます。",
    "parkFullTitle": "フンデルトヴァッサー・パーク & フンデルト・ウィンズカフェ",
    "parkStoryTitle": "海沿いを走ったら、アートの中を歩こう。",
    "parkStoryIntro": "色鮮やかな建物、曲がりくねった道、その間に育つ木々。フンデルトヴァッサーの世界を散策し、海を望むカフェでひと休みする牛島の午後へ。",
    "parkArtTitle": "アートから始まる散歩",
    "parkArtBody": "絵画・版画・生涯・環境建築・パークの五つの展示室で、芸術家の視点に触れてみましょう。",
    "parkPhotoTitle": "色彩を写真に",
    "parkPhotoBody": "鮮やかな建物と個性的な彫刻。歩く先々が旅の写真になります。",
    "parkNatureTitle": "自然と並んで",
    "parkNatureBody": "木々と曲線が調和する道をゆっくり歩き、自然を包み込む建築を感じてください。",
    "parkCafeTitle": "海を前にひと休み",
    "parkCafeBody": "フンデルト・ウィンズカフェで城山日出峰と牛島の海を眺めながら、名物U-Donutを楽しめます。",
    "parkTravel": "🕐 Coconaraから約40分",
    "parkHours": "09:30–18:00 · チケット販売17:00まで · 年中無休",
    "brandProofBroadcast": "テレビ番組に登場",
    "brandProofPrice": "明瞭な定価",
    "brandProofCare": "毎日2回の清掃・点検",
    "brandProofTime": "返却締切まで利用可能",
    "journeyTasteBenefit": "アイス・マグネット全商品割引",
    "journeyArtBenefit": "アートテーマパーク入場料割引",
    "journeyCafe": "フンデルトウィンズカフェ",
    "journeyCafeBenefit": "城山日出峰の海景・ドリンク割引",
    "tasteBaseTitle": "ベースから牛島ピーナッツ",
    "tasteBaseBody": "自家焙煎した牛島の丸ごとピーナッツを挽いてベースに加えるため、最初の一口から濃厚な香ばしさ。",
    "tasteRoastTitle": "その日使う分だけ毎日焙煎",
    "tasteRoastBody": "栽培・収穫・選別を自ら行い、毎日必要な量を焙煎。香りと食感を引き出します。",
    "tasteToppingTitle": "トッピングまで手作りの専門店",
    "tasteToppingBody": "自家製ピーナッツソースで焼いたアーモンド、ピーナッツのポン菓子、手作り「Hello Udo」クッキー。一杯を最後まで香ばしく仕上げます。",
    "broadcastCafe": "☕ フンデルトウィンズカフェ",
    "ferryBubble": "ココナラは下牛目洞港！",
    "fundingFocus": "ココナラが全額負担します。",
    "batteryBefore": "新型車両は牛島1周を基準に設計され、最大2周まで走行可能です。バッテリー消費は運転習慣によって変わります。",
    "batteryLead": "ゆとりを持って安全に観光するため、",
    "batteryRange": "1.5周",
    "batteryAfter": "を基準にご利用ください。",
    "batteryFine": "※ バッテリー切れの際は牽引料がかかります。ココナラは時間単位の利用制限なし。",
    "portSeongsan": "城山港",
    "portHaumokdong": "下牛目洞港",
    "routeEntering": "牛島へ行くとき",
    "routeLeaving": "牛島から帰るとき",
    "nextSailing": "次のフェリー出航時刻",
    "sailingInfo": "運航案内"
  }
}
;
