window.COCO_JOURNEY_COPY={
  "ko": {
    "routeFrom": "성산항",
    "routeTo": "우도 하우목동항",
    "routeTime": "약 15분 소요",
    "routeLabel": "성산항과 우도 하우목동항 사이 이동 안내",
    "crewTitle": "선원분께 먼저 물어보세요",
    "crewAsk": "정시 배를 놓치셨나요?",
    "crewAnswer": "30분에도 추가 출항하는 경우가 많아요.",
    "crewBoard": "배가 차면 출발해요. 미리 타고 기다려 주세요!",
    "crewDestination": "“하우목동항행 맞나요?”",
    "crewDestinationNote": "배표를 내실 때 목적지를 꼭 확인해 주세요.",
    "crewNote": "추가 출항은 현장 상황에 따라 달라집니다.",
    "paused": "멈추기",
    "play": "재생하기"
  },
  "en": {
    "routeFrom": "Seongsan Port",
    "routeTo": "Haumokdong Port, Udo",
    "routeTime": "About 15 minutes",
    "routeLabel": "Travel guide between Seongsan Port and Haumokdong Port on Udo",
    "crewTitle": "Ask the crew first",
    "crewAsk": "Missed the ferry on the hour?",
    "crewAnswer": "Extra ferries often leave at half past the hour, too.",
    "crewBoard": "The ferry leaves when it fills up. Please board early and wait on board!",
    "crewDestination": "“Is this ferry going to Haumokdong Port?”",
    "crewDestinationNote": "Please confirm the destination when you hand over your ticket.",
    "crewNote": "Extra departures depend on conditions at the port.",
    "paused": "Pause",
    "play": "Play"
  },
  "ms": {
    "routeFrom": "Pelabuhan Seongsan",
    "routeTo": "Pelabuhan Haumokdong, Udo",
    "routeTime": "Sekitar 15 minit",
    "routeLabel": "Panduan perjalanan antara Pelabuhan Seongsan dan Pelabuhan Haumokdong di Udo",
    "crewTitle": "Tanya kru terlebih dahulu",
    "crewAsk": "Terlepas feri yang berlepas setiap jam?",
    "crewAnswer": "Feri tambahan juga sering berlepas pada minit ke-30 setiap jam.",
    "crewBoard": "Feri bertolak apabila penuh. Sila naik lebih awal dan tunggu di dalam feri!",
    "crewDestination": "“Adakah feri ini menuju ke Pelabuhan Haumokdong?”",
    "crewDestinationNote": "Sila pastikan destinasi semasa menyerahkan tiket anda.",
    "crewNote": "Pelepasan tambahan bergantung pada keadaan di pelabuhan.",
    "paused": "Jeda",
    "play": "Main"
  },
  "zh-HK": {
    "routeFrom": "城山港",
    "routeTo": "牛島下牛目洞港",
    "routeTime": "約需15分鐘",
    "routeLabel": "城山港與牛島下牛目洞港之間的交通指南",
    "crewTitle": "先向船員問清楚",
    "crewAsk": "錯過整點開出的船了嗎？",
    "crewAnswer": "不少時候，半點也會加開班次。",
    "crewBoard": "船滿了就會開出，請提早上船等候！",
    "crewDestination": "「這班船是去下牛目洞港嗎？」",
    "crewDestinationNote": "交船票時，請務必確認目的地。",
    "crewNote": "是否加開班次，視乎現場情況。",
    "paused": "暫停",
    "play": "播放"
  },
  "zh-TW": {
    "routeFrom": "城山港",
    "routeTo": "牛島下牛目洞港",
    "routeTime": "約需15分鐘",
    "routeLabel": "城山港與牛島下牛目洞港之間的交通指南",
    "crewTitle": "先向船員確認",
    "crewAsk": "錯過整點出發的船了嗎？",
    "crewAnswer": "很多時候，半點也會加開班次。",
    "crewBoard": "船滿了就會出發，請提早上船等候！",
    "crewDestination": "「這班船是去下牛目洞港嗎？」",
    "crewDestinationNote": "交船票時，請務必確認目的地。",
    "crewNote": "是否加開班次，依現場情況而定。",
    "paused": "暫停",
    "play": "播放"
  },
  "ja": {
    "routeFrom": "城山港",
    "routeTo": "牛島・下牛目洞港",
    "routeTime": "所要時間 約15分",
    "routeLabel": "城山港と牛島・下牛目洞港の間の移動案内",
    "crewTitle": "まず船員に聞いてみましょう",
    "crewAsk": "毎時ちょうどの便に乗り遅れましたか？",
    "crewAnswer": "毎時30分にも臨時便が出ることがよくあります。",
    "crewBoard": "船が満員になると出発します。早めに乗船してお待ちください！",
    "crewDestination": "「この船は下牛目洞港行きですか？」",
    "crewDestinationNote": "乗船券を渡す際に、必ず行き先を確認してください。",
    "crewNote": "臨時便の運航は現地の状況によって異なります。",
    "paused": "一時停止",
    "play": "再生"
  }
}
;
